---
apiVersion: v1
kind: Service
metadata:
  name: color-provider-red
spec:
  selector:
    app: color-provider-red
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: color-provider-red
  name: color-provider-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-provider-red
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-tags': color-service,red
      labels:
        app: color-provider-red
    spec:
      containers:
        - env:
            - name: CONSUL_ENABLED
              value: "false"
            - name: APP_COLOR
              value: red
          image: localhost:32000/color-provider:1.0.0-SNAPSHOT
          name: color-provider-red
          ports:
            - containerPort: 8080
          resources: { }
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}