---
apiVersion: v1
kind: Service
metadata:
  name: color-provider-blue
spec:
  selector:
    app: color-provider-blue
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: color-provider-blue
  name: color-provider-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-provider-blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-tags': color-service,blue
      labels:
        app: color-provider-blue
    spec:
      containers:
        - env:
            - name: CONSUL_ENABLED
              value: "false"
            - name: APP_COLOR
              value: blue
          image: localhost:32000/color-provider:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: color-provider-blue
          ports:
            - containerPort: 8080
          resources: { }
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}